modLoader="javafml"
loaderVersion="[31,)" # 1.16+
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/WaterDripSound/issues"
[[mods]]
modId="waterdripsound"
version="0.2.1"
displayName="Drip Sounds"
displayURL="https://github.com/PieKing1215/WaterDripSound"
logoFile="logo.png"
authors="PieKing1215"
description='''Makes drip particles play a sound (and other related changes).'''

[[dependencies.waterdripsound]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.44,)" # first 1.15 version with mixins
    ordering="NONE"
    side="BOTH"
[[dependencies.waterdripsound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waterdripsound]]
    modId="cloth-config2"
    mandatory=true
    versionRange="[3.0,)"
    ordering="NONE"
    side="CLIENT"
